In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("customer.csv")

In [5]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [6]:
df=df.iloc[:,2:5]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.3)

In [41]:
y_train.head()

38    No
43    No
44    No
46    No
34    No
Name: purchased, dtype: object

In [55]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [58]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [59]:
X_train = oe.transform(X_train)

In [60]:
X_train

array([[2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 1.]])

In [61]:
X_train_label=pd.DataFrame(X_train,columns=['review','education'])

In [62]:
X_train_label.head()

review  education
0     2.0        0.0
1     0.0        2.0
2     1.0        1.0
3     0.0        2.0
4     1.0        0.0

In [63]:
from sklearn.preprocessing import LabelEncoder

In [64]:
le=LabelEncoder()

In [65]:
le.fit(y_train)

LabelEncoder()

In [66]:
y_train=le.transform(y_train)

In [67]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0])

In [68]:
y_train_label=pd.DataFrame(y_train,columns=['purchased'])

In [69]:
y_train_label.head()

purchased
0          0
1          0
2          0
3          0
4          0

In [70]:
df=pd.read_csv('cars.csv')

In [71]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [74]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

In [75]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [76]:
X_train,X_test,y_train,y_test=train_test_split(df[['fuel','owner']],df['selling_price'],test_size=0.2)

In [77]:
X_train.head()

fuel         owner
6931  Diesel   Third Owner
1522  Petrol   First Owner
4010  Diesel  Second Owner
1517  Petrol  Second Owner
7817  Diesel   First Owner

In [79]:
from sklearn.preprocessing import OneHotEncoder

In [80]:
ohe=OneHotEncoder(sparse_output=False,drop='first')

In [81]:
ohe.fit(X_train)

OneHotEncoder(drop='first', sparse_output=False)

In [82]:
X_train_trans = ohe.transform(X_train)
X_test_trans = ohe.transform(X_test)

In [83]:
X_train_trans

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 1.]])

In [88]:
import numpy as np

In [102]:
X_train_np = np.hstack((X_train[['fuel','owner']].values,X_train_trans))
X_train_np.shape

(6502, 9)

In [95]:
from sklearn.compose import ColumnTransformer

In [96]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(sparse_output=False,drop='first'),['fuel','owner'])
],remainder='passthrough')

In [110]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [106]:
df_trans = transformer.fit_transform(df)

In [107]:
pd.DataFrame(df_trans)

0    1    2    3    4    5    6        7       8       9
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0   Maruti  145500  450000
1     1.0  0.0  0.0  0.0  1.0  0.0  0.0    Skoda  120000  370000
2     0.0  0.0  1.0  0.0  0.0  0.0  1.0    Honda  140000  158000
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  Hyundai  127000  225000
4     0.0  0.0  1.0  0.0  0.0  0.0  0.0   Maruti  120000  130000
...   ...  ...  ...  ...  ...  ...  ...      ...     ...     ...
8123  0.0  0.0  1.0  0.0  0.0  0.0  0.0  Hyundai  110000  320000
8124  1.0  0.0  0.0  1.0  0.0  0.0  0.0  Hyundai  119000  135000
8125  1.0  0.0  0.0  0.0  0.0  0.0  0.0   Maruti  120000  382000
8126  1.0  0.0  0.0  0.0  0.0  0.0  0.0     Tata   25000  290000
8127  1.0  0.0  0.0  0.0  0.0  0.0  0.0     Tata   25000  290000

[8128 rows x 10 columns]